export const data = [
  {
    adcode: '330100',
    casts: [
      {
        date: '2023-08-20',
        daypower: '4',
        daytemp: '34',
        daytemp_float: '34.0',
        dayweather: '雷阵雨',
        daywind: '东',
        nightpower: '4',
        nighttemp: '25',
        nighttemp_float: '25.0',
        nightweather: '多云',
        nightwind: '东',
        week: '7',
      },
      {
        date: '2023-08-21',
        daypower: '4',
        daytemp: '34',
        daytemp_float: '34.0',
        dayweather: '多云',
        daywind: '西南',
        nightpower: '4',
        nighttemp: '25',
        nighttemp_float: '25.0',
        nightweather: '雷阵雨',
        nightwind: '西南',
        week: '1',
      },
      {
        date: '2023-08-22',
        daypower: '≤3',
        daytemp: '33',
        daytemp_float: '33.0',
        dayweather: '雷阵雨',
        daywind: '西南',
        nightpower: '≤3',
        nighttemp: '24',
        nighttemp_float: '24.0',
        nightweather: '小雨',
        nightwind: '西南',
        week: '2',
      },
      {
        date: '2023-08-23',
        daypower: '≤3',
        daytemp: '32',
        daytemp_float: '32.0',
        dayweather: '小雨',
        daywind: '北',
        nightpower: '≤3',
        nighttemp: '24',
        nighttemp_float: '24.0',
        nightweather: '阴',
        nightwind: '北',
        week: '3',
      },
    ],
    city: '杭州市',
    province: '浙江',
    reporttime: '2023-08-20 22:01:56',
  },
];
